### ISSUE TITLE
Server Error - logging in

### ISSUE THREAD

**Issue by JohnnyKHU** [alan412/ev3hub#59]
Hello! This is such a nice solution and is very excellent you have contributed it to the community. The most senior team I'm coaching has started to use ev3hub. This week, however, they are having log in failures (500 internal system error - see screen shot below). Account name is RogueRobots. I'm guessing something got snarled up in the filestore?

The kids have a scrimmage coming up so any help appreciated.
--------------------------------------
```
500 Internal Server Error
The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "/home/ev3hub/ev3hub/venv3/lib/python3.6/site-packages/cherrypy/_cprequest.py", line 628, in respond
    self._do_respond(path_info)
  File "/home/ev3hub/ev3hub/venv3/lib/python3.6/site-packages/cherrypy/_cprequest.py", line 687, in _do_respond
    response.body = self.handler()
  File "/home/ev3hub/ev3hub/venv3/lib/python3.6/site-packages/cherrypy/lib/encoding.py", line 219, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/home/ev3hub/ev3hub/venv3/lib/python3.6/site-packages/cherrypy/_cpdispatch.py", line 54, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "ev3hub.py", line 135, in login
    return self.show_mainpage(username)
  File "ev3hub.py", line 62, in show_mainpage
    ev3P = self.get_project()
  File "ev3hub.py", line 50, in get_project
    ev3p = self.users.get_project(username, project)
  File "/home/ev3hub/ev3hub/users.py", line 215, in get_project
    projectName = self.get_projectlist(username)[0]['name']
  File "/home/ev3hub/ev3hub/users.py", line 264, in get_projectlist
    up = UserProjects(username)
  File "/home/ev3hub/ev3hub/users.py", line 41, in __init__
    self.remove_expired_projects()
  File "/home/ev3hub/ev3hub/users.py", line 84, in remove_expired_projects
    projectDir = os.path.join(self.path(), getSHA(project))
TypeError: 'str' object is not callable
```

**Comment by alan412** [comment]
Thank you for the great bug report.  I have fixed it.

**Comment by alan412** [comment]
Thanks for the great report.  Fixed now.
